[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
anchor_movie_review_program = "9BQJitihiEE5fcK4USjfftUepCiXBVxLECmLxe9VeWXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/durvesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
